---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "mqtt-sub-deployment"
spec:
  selector:
    matchLabels:
      app: "mqtt-sub"
  replicas: 1
  template:
    metadata:
      labels:
        app: "mqtt-sub"
    spec:
      containers:
        - name: "mqtt-sub"
          image: andschneider/keda-mqtt-example:v0.0.2
          args: [ "-topic", "keda-mqtt-example" ]
          imagePullPolicy: IfNotPresent
          env:
            - name: HOST_URL
              value: tcp://mosquitto-service:1883
